version: '3.8'

services:
  prestashop:
    image: prestashop/prestashop:latest
    container_name: prestashop
    restart: unless-stopped
    environment:
      - DB_SERVER=db
      - DB_NAME=prestashop
      - DB_USER=prestashop
      - DB_PASSWD=prestashop_password
      - PS_DOMAIN=localhost:8080
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_FOLDER_ADMIN=admin
      - PS_FOLDER_INSTALL=install
      - PRESTASHOP_REDIS_ENABLED=1
      - PRESTASHOP_REDIS_HOST=redis
    ports:
      - "8080:80"
    volumes:
      - prestashop_data:/var/www/html
    depends_on:
      - db
      - redis
    networks:
      - prestashop_network

  db:
    image: percona:latest
    container_name: percona
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - prestashop_network

volumes:
  prestashop_data:
  db_data:
  redis_data:
networks:
    prestashop_network: